-- Bundle all source files into one self-contained Lua file.
-- Usage: F:/soft/lua/lua.exe bundle.lua
-- Output: irish_engine_bundled.lua

local function read(path)
  local f = io.open(path, "rb")
  if not f then return nil end
  local c = f:read("*a")
  f:close()
  return c
end

local function write(path, content)
  local f = io.open(path, "wb")
  if not f then return nil end
  f:write(content)
  f:close()
end

local files = {
  "passes/_shared.lua",
  "passes/01_polarity.lua",
  "passes/02_stress.lua",
  "passes/03_eclipsis.lua",
  "passes/04_cluster_simplify.lua",
  "passes/05_mutated_fricatives.lua",
  "passes/06_vocalization.lua",
  "passes/06d_anticipatory_raising.lua",
  "passes/07_nasalization.lua",
  "passes/08_slender_coda.lua",
  "passes/09_consonants.lua",
  "passes/09b_vowel_adjunct.lua",
  "passes/10_vowels.lua",
  "passes/11_unstressed_reduction.lua",
  "passes/12_epenthesis.lua",
  "passes/13_sonorants.lua",
  "passes/14_final_cleanup.lua",
  "passes/init.lua",
  "irish_engine_new.lua",
}

local header = [[
-- Irish G2P Engine — bundled single-file version
-- Auto-generated by bundle.lua
-- Connacht dialect grapheme-to-phoneme pipeline (16 passes)

]]

local parts = { header }
for _, f in ipairs(files) do
  local content = read(f)
  if content then
    parts[#parts + 1] = "--[[" .. f .. "]]\n"
    parts[#parts + 1] = content
    parts[#parts + 1] = "\n\n"
  else
    io.stderr:write("ERROR: could not read " .. f .. "\n")
  end
end

write("irish_engine_bundled.lua", table.concat(parts))
print("Written irish_engine_bundled.lua")
