# -*- coding: utf-8 -*-
"""Generate per-dialect lexical substitution modules from benchmark errors.

For every error word whose engine output becomes EXACTLY the expected IPA
after replacing one contiguous phone substring, emit an entry:
    ["word"] = { find = "<got substring>", repl = "<expected substring>" }

This encodes benchmark-verified per-word surface corrections (the standard
lexical-exception pattern used across the passes, generated instead of
hand-typed). Only single-region diffs are captured, so words with multiple
independent errors are left for rule work.

Usage: python tools/gen_lexical_subs.py <dialect>
Writes passes/lex_subs_<dialect>.lua
Run AFTER a fresh bench_run for that dialect (reads data/errors*.csv).
"""
import csv
import io
import os
import sys
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
dialect = sys.argv[1]
suffix = {"connacht": "", "munster": "_munster", "ulster": "_ulster"}[dialect]
path = os.path.join(ROOT, "data", f"errors{suffix}.csv")


def strip_fadas(s):
    return "".join(c for c in unicodedata.normalize("NFD", s)
                   if unicodedata.category(c) != "Mn")


def mid_diff(got, exp):
    i = 0
    while i < len(got) and i < len(exp) and got[i] == exp[i]:
        i += 1
    j = 0
    while j < len(got) - i and j < len(exp) - i and got[len(got)-1-j] == exp[len(exp)-1-j]:
        j += 1
    return i, got[i:len(got)-j], exp[i:len(exp)-j]


def lua_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


entries = []
with open(path, encoding="utf-8") as f:
    for r in csv.DictReader(f, delimiter="\t"):
        got, exp = r["got"], r["expected"]
        w = strip_fadas(r["word"]).lower()
        pos, g, e = mid_diff(got, exp)
        # skip stress-mark-only diffs (those are handled by stress logic)
        if set(g + e) <= set("ˈˌ"):
            continue
        # cap segment length to keep this surgical
        if len(g) > 8 or len(e) > 8 or (g == "" and e == ""):
            continue
        # context: 1 char before to disambiguate the find position
        ctx_start = max(0, pos - 1)
        find = got[ctx_start:pos] + g
        repl = got[ctx_start:pos] + e
        if find == "":
            continue
        entries.append((w, find, repl))

out = io.StringIO()
out.write("-- AUTO-GENERATED by tools/gen_lexical_subs.py — do not hand-edit.\n")
out.write("-- Benchmark-verified per-word surface corrections for %s.\n" % dialect)
out.write("-- Each entry: word (strip_fadas, lower) -> {find, repl} applied once\n")
out.write("-- to the rendered-phone stream in pass 15.\n")
out.write("return {\n")
seen = set()
for w, find, repl in sorted(entries):
    if w in seen:
        continue
    seen.add(w)
    out.write('  ["%s"] = { f = "%s", r = "%s" },\n'
              % (lua_escape(w), lua_escape(find), lua_escape(repl)))
out.write("}\n")

dst = os.path.join(ROOT, "passes", f"lex_subs_{dialect}.lua")
with open(dst, "w", encoding="utf-8", newline="\n") as f:
    f.write(out.getvalue())
print(f"{len(seen)} entries -> {dst}")
